Iter1
igortoigildin/go-rewards-app pull request #1
Opened 2024-08-03 18:17 UTC by igortoigildin

2024-08-26 09:54 UTC, tmvrus requested changes
Работа хорошая, но есть недостатки.

2024-08-26 09:54 UTC, tmvrus commented on cmd/gophermart/main.go
> +		logger.Log.Info("error while initializing logger", zap.Error(err))
у меня тут два вопроса:
- как  можно что-то логировать если логер не был проинициализован
- как можно ли дальше работать если нет логера, `Info` выполнение не прервет

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/orders/order.go
> +		tx.Rollback()
ошибки Rollback следует обрабатывать, иначе рисуем не узнать что транзакции не откатываются

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/orders/order.go
> +		"VALUES ($1, $2, $3, now() AT TIME ZONE 'MSK')"
в языке есть multiline string
https://golang.cafe/blog/how-to-write-multiline-string-in-go-golang
существенно удобнее чем +

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/orders/order.go
> +	err := rep.db.QueryRowContext(ctx, `SELECT user_id FROM orders WHERE number = $1;`, order.Number).Scan(&userID)
в ситуации когда два входящих запроса одновременно сохраняют заказ можно получить ошибку, потому что оба сначала прочитаю что заказа нет в базе, а затем попробуют его вставить.
Почему бы не воспользоваться тут конструкцией ON CONFLCIT или просто обрабатывать ошибку нарушения уникальность от Postgres?

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/orders/order.go
> +func (rep *OrderRepository) SelectForAccrualCalc() ([]int64, error) {
почему этот метод не поддерживает контекст, хотя остальные поддерживают ?

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/withdrawals/withdrawal.go
> +		tx.Rollback()
тут тоже не обрабатывются ошибки rollback

2024-08-26 09:54 UTC, tmvrus commented on internal/api/auth.go
> +		user, err := tokenService.FindUserByToken(context.Background(), hash[:])
`context.Background()` ничего не гарантирует и никак не связывает входящий запрос с запросом в `tokenService`, контекст вполне можно взять из `http.Request`

2024-08-26 09:54 UTC, tmvrus commented on internal/api/order.go
> +		defer cancel()
нет смысла создавать отменяемый контекст, если отменяем мы его только в defer, возможно, тут больше подойдет контекст с таймаутом.

2024-08-26 09:54 UTC, tmvrus commented on internal/api/order.go
> +		defer cancel()
более того, этот подход повторяется в каждом хендлере, возможно стоит сделать middleware где в каждый запрос будет добавляться контекст с таймаутом.

2024-08-26 09:54 UTC, tmvrus commented on internal/api/order.go
> +		valid, err := ValidateOrder(string(number))
`string(number)` три раза вычисляется в хендлере, может вычислить один раз и переиспользовать?

2024-08-26 09:54 UTC, tmvrus commented on internal/api/registration.go
> +			case errors.Is(err, ErrDuplicateLogin):
эта ошибка используется только в этом месте, как ее может вернуть userService?

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/user/user.go
> +			return ErrDuplicateLogin
это так не работеат, что бы errors.Is мог вернуть вменяемый результат, нужно что бы ошибка была одна и та же.

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/user/user.go
> +			return ErrDuplicateLogin
к ErrRecordNotFound это тоже полностью относится

2024-08-26 09:54 UTC, tmvrus commented on internal/storage/postgres/user/user.go
> +			return ErrDuplicateLogin
https://play.golang.com/p/uukUcghG0Zo

2024-08-26 09:54 UTC, tmvrus commented on internal/api/withdraw.go
> +			rw.WriteHeader(http.StatusInternalServerError)
return?

2024-08-26 09:54 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +var statusProcessed string = "PROCESSED"
думаю логичнее использовать константы

2024-08-26 09:54 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +		err = o.OrderRepository.UpdateOrderAndBalance(context.Background(), order)
тут вполне можно было использовать контекст с таймаутом и для UpdateOrderAndBalance и для http-запроса

2024-08-26 09:54 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +func (o *OrderService) UpdateAccruals(cfg *config.Config, order *orderEntity.Order) {
у метода есть существенный недостаток: он вызывается только когда приходит запрос на создание заказа.
 Представь ситуацию - пришло 10 запросов, запустилось 10 горутин и каждая крутится в цикле ожидая финального статуса для заказа, в этом момент  мы обновляем сервис что бы исправить баг, и горутины умирают. 
 Все, для этих 10 заказов уже никогда не будет произведен рассчет.

2024-08-26 09:54 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +		resp, err := http.Get(url)
По условиям технического задания, сервис рассчета может вернуть
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
но это никак не обрабатывается

2024-08-26 09:54 UTC, tmvrus commented on internal/service/domain/order/contract.go
> +	SelectForAccrualCalc() ([]int64, error)
этот метод где-то вызывается?

2024-08-27 16:04 UTC, igortoigildin commented on cmd/gophermart/main.go
> +		logger.Log.Info("error while initializing logger", zap.Error(err))
исправил на log.Fatalf

2024-08-27 16:06 UTC, igortoigildin commented on internal/storage/postgres/orders/order.go
> +		tx.Rollback()
добавил обработку ошибки для Rollback() во всех случаях

2024-08-27 16:20 UTC, igortoigildin commented on internal/storage/postgres/orders/order.go
> +		"VALUES ($1, $2, $3, now() AT TIME ZONE 'MSK')"
обновил

2024-08-27 19:37 UTC, igortoigildin commented on internal/storage/postgres/orders/order.go
> +	err := rep.db.QueryRowContext(ctx, `SELECT user_id FROM orders WHERE number = $1;`, order.Number).Scan(&userID)
исправил с помощью ON CONFLICT

2024-08-28 08:18 UTC, igortoigildin commented on internal/storage/postgres/withdrawals/withdrawal.go
> +		tx.Rollback()
добавил

2024-08-28 10:24 UTC, igortoigildin commented on internal/api/auth.go
> +		user, err := tokenService.FindUserByToken(context.Background(), hash[:])
обновил на контекст из http.Request

2024-08-28 10:25 UTC, igortoigildin commented on internal/api/order.go
> +		defer cancel()
во всех случаях убрал отменяемый контекст, в хендлеры добавил middleware с таймаутами.

2024-08-28 10:38 UTC, igortoigildin commented on internal/api/order.go
> +		valid, err := ValidateOrder(string(number))
обновил

2024-08-28 10:39 UTC, igortoigildin commented on internal/api/registration.go
> +			case errors.Is(err, ErrDuplicateLogin):
обновил обработку ошибок

2024-08-28 10:39 UTC, igortoigildin commented on internal/storage/postgres/user/user.go
> +			return ErrDuplicateLogin
обновил обработку ошибок

2024-08-28 10:39 UTC, igortoigildin commented on internal/api/withdraw.go
> +			rw.WriteHeader(http.StatusInternalServerError)
добавил

2024-08-28 10:40 UTC, igortoigildin commented on internal/service/domain/order/accruals.go
> +var statusProcessed string = "PROCESSED"
обновил

2024-08-28 11:09 UTC, igortoigildin commented on internal/service/domain/order/accruals.go
> +		err = o.OrderRepository.UpdateOrderAndBalance(context.Background(), order)
полностью поменял реализацию accruals.go. Теперь запросы к accruals API не зависят от поступления новых запросов по заказам. В новой версии в SelectForAccrualCalc и UpdateOrderAndBalance добавляю контекст с таймаутом.

2024-08-28 11:10 UTC, igortoigildin commented on internal/service/domain/order/accruals.go
> +func (o *OrderService) UpdateAccruals(cfg *config.Config, order *orderEntity.Order) {
поменял реализацию accruals.go. Теперь запросы к accruals API не зависят от поступления новых запросов по заказам.

2024-08-28 11:11 UTC, igortoigildin commented on internal/service/domain/order/accruals.go
> +		resp, err := http.Get(url)
добавил реализацию функции wait в accrual.go

2024-08-28 11:12 UTC, igortoigildin commented on internal/service/domain/order/contract.go
> +	SelectForAccrualCalc() ([]int64, error)
теперь да, поменял реализацию accruals.go

2024-08-28 11:26 UTC, igortoigildin commented on internal/storage/postgres/orders/order.go
> +func (rep *OrderRepository) SelectForAccrualCalc() ([]int64, error) {
добавил поддержку контекста

2024-08-30 09:40 UTC, tmvrus approved these changes

2024-08-30 09:40 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +		defer cancel()
вот это кстати "memory leak" cancel будет вызван только по выходу из ф-и, а тут он не предусмотрен в принципе. на каждой итерации цикла будет добавляться новый defer в очередь, а вызываться не будет никогда. Рекомендую линтер(golang ci lint) поставить он такие вещи умеет ловить.

2024-08-30 09:40 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +			return
Не рекомендую так делать, например можно быть сетевой сбой, база вернет ошибку, мы завершим воркер. когда сеть снова начнет работать, а воркер уже не запустится. Придется перезапускать приложение.

2024-08-30 09:40 UTC, tmvrus commented on internal/service/domain/order/accruals.go
> +		for a := 1; a <= numJobs; a++ {
луче итерировать сразу по каналу `for order := range results ` такой цикл сам завершится когда канал закроют и не нужно будет следить за счетчиком)

2024-10-11 15:37 UTC, merged